sul-dlss/hydrus

Gemfile
Gemfile.lock

Update libv8 to a version that works with Clang 8.00 (MacOS 10.12)

---

spec/models/hy_time_spec.rb
spec/models/hydrus/item_spec.rb

Allows testing for remote workers who aren't in the Pacific Time Zone.

Don't expect Pacific time when testing.

---

Gemfile

This is how things are done in Rails 4.  This may be the cause of:
```
Sprockets::FileNotFound: couldn't find file 'bootstrap'
```
that we see when deploying via capistrano

Move gems out of the assets group

---

config/deploy.rb

rails-secrets was added in a previous commit, but the deploy was not
adjusted to link that file.

link config/secrets.yml on a deploy

---

app/models/hydrus/item.rb
config/environments/development.rb
lib/tasks/ci.rake
spec/features/item_create_spec.rb
spec/models/hydrus/item_spec.rb

- fixes #42 and adds a test
- remove auto rebuilding of rdoc each time rake ci is run (this doesn't work now anyway)
- change purl-dev to purl-test in development.rb config (purl-dev doesn't exist anymore and causes an exception in development when you try to edit an item)

ensure not all contributors are blank

---

config/environments/dortest.rb

Currently we get this warning
```
$ bundle exec rails c dortest
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
* development - set it to false
* test - set it to false (unless you use a tool that preloads your test environment)
* production - set it to true
Loading dortest environment (Rails 4.2.9)
```

Eager load on dortest

---

app/models/hydrus/admin_policy_object.rb

Because with the change to Shibboleth authentication, Argo is only able
to see SDR stemmed workgroup membership.
Fixes #169

Use SDR stemmed workgroups for new APOs

---

config/jetty.yml
lib/tasks/ci.rake

This allows us to do `rake jetty:start hydrus:refreshfix` and it won't
try to proceed to the second task before the first is complete.

Move jetty configuration to the yaml file

---

spec/support/feature_sessions.rb

This adjusts our test headers so they do the same

Shibboleth sets the email as the header

---

Gemfile
Gemfile.lock
lib/tasks/ci.rake

This avoids a warning:
```
lib/tasks/ci.rake:1: warning: already initialized constant ZIP_FILE
```

Use the hydra_jetty_verison setter

---

lib/tasks/ci.rake

That gem isn't loaded in production

Only reference jettywrapper when in test

---

config/deploy.rb

This was a workaround for a problem in the indexing system that has
since been resolved

Stop indexing workflows on deploy

---

Gemfile.lock

That gem was yanked from rubygems

Update jettywrapper so it doesn't require the logger gem

---

app/helpers/hydrus_form_helper.rb
spec/helpers/hydrus_form_helper_spec.rb

There is no `RELS-EXT` method on the object.
Fixes #243

Use the datastreams hash accessor rather than send

---

.travis.yml
Gemfile
Gemfile.lock
README.md
app/models/hydrus/admin_policy_object.rb
app/models/hydrus/collection.rb
app/models/hydrus/generic_object.rb
app/models/hydrus/item.rb
app/models/hydrus/rights_metadata_ds.rb
app/services/item_service.rb
config/application.rb
config/environment.rb
config/initializers/dor_services_client.rb
config/settings.yml
docker-compose.yml
spec/features/contact_spec.rb
spec/features/models/admin_policy_object_spec.rb
spec/models/hydrus/collection_spec.rb
spec/models/hydrus/generic_object_spec.rb
spec/support/rubydora_transactions_monkeypatch.rb

Fixes #228 
Also:
* Configure TravisCI build to use docker-compose instead of recreating it
* Add dor-services-app to the docker-compose config
* Upgrade dor-services to 6.1.x 
* Work around underlying changes to Dor::Editable
* Bump to latest dor-services-client and dor-services to pick up new patches (needed because of bugs discovered doing this work)
* Remove deprecation warnings and use client for opening new versions

Use dor-services-client for object registration and opening new versions

---

config/assemblyWF_hydrus.xml

This aligns Hydrus with the workflows that are retrieved from dor-services-app
Fixes #255

Give a workflow an id

---

Gemfile
Gemfile.lock

Rails 5.2.2 is incompatible with sqlite 1.4
Refs [rails/rails#35153](https://github.com/rails/rails/issues/35153)

Pin sqlite to ~> 1.3.13

---

.gitignore
docker-compose.yml
spec/fixtures/workflow_xml/druid_oo000oo0000.xml
spec/fixtures/workflow_xml/druid_oo000oo0001.xml
spec/fixtures/workflow_xml/druid_oo000oo0002.xml
spec/fixtures/workflow_xml/druid_oo000oo0003.xml
spec/fixtures/workflow_xml/druid_oo000oo0004.xml
spec/fixtures/workflow_xml/druid_oo000oo0005.xml
spec/fixtures/workflow_xml/druid_oo000oo0006.xml
spec/fixtures/workflow_xml/druid_oo000oo0007.xml
spec/fixtures/workflow_xml/druid_oo000oo0008.xml
spec/fixtures/workflow_xml/druid_oo000oo0009.xml
spec/fixtures/workflow_xml/druid_oo000oo0010.xml
spec/fixtures/workflow_xml/druid_oo000oo0011.xml
spec/fixtures/workflow_xml/druid_oo000oo0012.xml
spec/fixtures/workflow_xml/druid_oo000oo0013.xml

This is necessary because the workflow server image had been updated to require a database.
We also turn off the STOMP notifications.

Add a database for the workflow service to the docker build

---

app/mailers/hydrus_mailer.rb
config/application.rb

This is already required in the spec_helper, so it didn't show up
as a test failure.  Also switch to eager_load_paths for Rails 5
Fixes #287

Require hydrus to avoid a NoMethodError

---

app/models/hydrus/collection.rb

There is no need to generate a DC datastream for APOs

---

app/models/hydrus/item.rb

This wasn't doing anything and dor-services-app is going to stop accepting it

Stop using a deprecated parameter: create_workflows_ds

---

app/helpers/application_helper.rb

A friendly PR to anonymizeIP for sdr.stanford.edu as we do this throughout our public portfolio

Set anonymizeIP true for Google Analytics

---

config/initializers/dor_config.rb
config/initializers/okcomputer.rb
config/settings.yml
docker-compose.yml

Do this for consistency. See also the same approach in Argo: https://github.com/sul-dlss/argo/pull/1468

Use token generated by containerized dor-services-app

---

.rubocop_todo.yml
app/models/hydrus/item.rb
spec/models/hydrus/item_spec.rb

It has already been removed in dor-services-app: https://github.com/sul-dlss/dor-services-app/pull/349

Dump poorly named and unnecessary hash arg when opening versions

---

Gemfile.lock
config/initializers/dor_services_client.rb
config/settings.yml
docker-compose.yml

This is no longer required, and in fact can break the client if the header value (from shared_configs) is unset. This is what broke the workflow service connection to dor-services-app.

Remove token_header keyword arg when configuring dor-services-client

---

spec/spec_helper.rb

Telling simplecov it's a Rails app means it will give more accurate stats on code coverage.
N/A

tell simplecov it's a rails app

---

app/controllers/hydrus_solr_controller.rb
lib/tasks/fixtures.rake
lib/tasks/hydrus.rake
spec/controllers/hydrus_solr_controller_spec.rb
spec/features/hydrus_solr_controller_spec.rb

The SearchService.solr is deprecated and should not be used.
n/a

Avoid using the deprecated SearchService.solr method

---

Gemfile
Gemfile.lock
app/models/hydrus/processable.rb
spec/features/models/item_spec.rb
spec/models/hydrus/processable_spec.rb

This prevents the workflow service from logging deprecation notices in honeybadger.
Deprecation errors logged in honeybadger: https://app.honeybadger.io/projects/58890/faults/54851492
n/a

Use a non deprecated workflow update method

---

Gemfile
Gemfile.lock

Previously was pinned to 0.4 for rails 4.2, but we've since upgrade to rails 5.2

Update to the latest mysql gem

---

Gemfile
Gemfile.lock

see comment in `Gemfile` for explanation.  before this fix, attempting to deploy to stage resulted in an error, noted in a comment below.
with the fix in this branch, deployment to stage succeeded.

re-pin mysql2 to a version we can deploy successfully on the current VM

---

config/schedule.rb

our nightly cron job generates a bunch of noise to email, for starters, we could just do this weekly, and secondly, maybe logging it will suppress the email?
attempt to address #393

set cron job to weekly and try to log output

---

app/uploaders/file_uploader.rb

Addresses #391 
see https://github.com/carrierwaveuploader/carrierwave#large-files

tell carrierwave to use move instead of copy during uploads

---

spec/features/item_versioning_spec.rb

Failure to provide a version is deprecated
n/a

Provide a version when creating a workflow

---

Gemfile
Gemfile.lock

This should prevent one of the many Gem::Specification#rubyforge_project= deprecations
n/a

Update to the latest coffee-script

---

.gitignore
app/controllers/object_files_controller.rb
app/models/hydrus/contentable.rb
app/models/hydrus/object_file.rb
app/uploaders/file_uploader.rb
config/deploy.rb
config/environment.rb
config/routes.rb
config/settings.yml
lib/tasks/fixtures.rake
spec/controllers/object_files_controller_spec.rb
spec/features/home_page_spec.rb
spec/features/item_create_spec.rb
spec/features/item_edit_spec.rb
spec/features/models/object_file_spec.rb
spec/features/object_files_controller_spec.rb
spec/models/hydrus/contentable_spec.rb
spec/support/helpers.rb

Fixes #392 
Verified on hydrus-stage
- Coordinate deployment with Hannah - currently the week of Feb 3 looks good
- After deploy:
- confirm that the previous insecure `/opt/app/hydrus/hydrus/current/public/uploads` symlink is gone.
- confirm that the new `/opt/app/hydrus/hydrus/current/uploads` symlink exists and goes to `/opt/app/hydrus/hydrus/shared/uploads`, which goes to `/data/hydrus-files`
- test by uploading a file to a new test object and confirm you can't download that file from hydrus in a private browser (not logged in) 
- publish the test object and verify it accessioned correctly with a PURL
- test a download of a file from a previously created object
- After verified working, we should remove the now unused symlink that goes from `/opt/app/hydrus/hydrus/shared/public/uploads …

Authenticate file downloads - requires server updates to deploy

---

Gemfile
Gemfile.lock

To get fresh coverage data with every PR (again).
This PR reverts simplecov to 0.17 to get coverage data reported. Some other dependency updates came along for the ride.
The most recent build to get coverage data was Jan 27.
n/a
n/a
If so, please confirm:

fix code coverage reporting

---

config/initializers/devise.rb

Newly upgraded Centos 7/Apache 2.4/Shib ??  machines seem to pass through empty REMOTE_USER headers instead of omitting  the header altogether.

Guard against an empty REMOTE_USER header

---

spec/features/hydrus_solr_controller_spec.rb

We no longer look in XML for tags (in dor-services-app), so update the tests to reflect this. We did the same in Argo yesterday.
No.
no.

Fix test setup

---

.travis.yml
README.md

add newer ruby to travis build

---

config/initializers/dor_config.rb
config/settings.yml

This removes a deprecation warning that displays in testing.
Running the test suite
none

Remove deprecated dor-services config

---

app/models/hydrus/item.rb
spec/models/hydrus/item_spec.rb

Fedora rejects updates where the label is longer than 255 characters.
Fixes #430 
Test suite
none

Truncate Fedora 3 label

---

Gemfile
Gemfile.lock
app/models/hydrus/processable.rb

#91  Why was this change made?
Not passing a version is deprecated and will cause an error when support for that is removed from workflow-server-rails
Test suite.
none

Pass a version when deleting the workflow

---

app/views/hydrus_items/edit.html.erb
app/views/hydrus_items/show.html.erb

Fixes #437
Embargo dates are persisted as UTC in Fedora and Solr, and have been for ~8 years. When an embargo date, set to the beginning of the specified day in UTC, is persisted it should be noted that the date as originally set assumed Pacific time. Use the existing HyTime model to handle the display conversion. No data remediation is needed.
Tested with an affected object in stage.
None

Convert embargo date to Pacific when displaying

---

.travis.yml

No longer using ruby 2.5.3 (new vms have ruby 2.7.1)
testing with app running 2.7.1 on new sul-hydrus-stage
none

the new vms have ruby 2.7.1 deployed

---

.travis.yml
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

coveralls integration with github is flaky, this swaps it out for codeclimate
by confirming the integration works here
README updated with new badge

swap out coveralls for code climate

---

app/assets/stylesheets/styles.css.scss
app/assets/stylesheets/sul_chrome/sul_chrome_base.scss
app/views/layouts/application.html.erb

Fixes #454
To restore image assets.
Deployed to stage and confirmed working.
None

Reference images using helpers

---

config/settings.yml

sul-purl-test is being decommissioned for naming consistency. It will be
aliased to sul-purl-stage, but for visibility we should probably rename
it everywhere.

Rename sul-purl-test to sul-purl-stage

---

app/indexers/identifiable_indexer.rb

It is used throughout Hydrus, but Argo doesn't use it anymore.

Index objectId_ssim

---

config/initializers/okcomputer.rb

1. Fixes the uploads folder status check (the folder moved, but I didn't update the check).
2. Proposed fix to the fedora URL check (allow a 302 to register as ok, as this still indicates the fedora URL is reachable)
On -stage manually

fix fedora and upload status checks

---

app/controllers/application_controller.rb
app/controllers/datastreams_controller.rb
app/controllers/events_controller.rb
spec/controllers/datastreams_controller_spec.rb

Connects to https://app.honeybadger.io/projects/49897/faults/48659064
This bug, which is not triggered very often, was caused by the upgrade to Rails 5. We adjusted the call  in the events controller but not in the datastreams controller to avoid calling a method that is no longer defined on `ActionController::Parameters`.
As part of this work, reduce duplication of code by moving a now-identical method into `ApplicationController`.
CI
None

Avoid NoMethodError in datastreams controller

---

.rspec
spec/spec_helper.rb

So when running a single spec file, it defaults to document format.  The default spec format is progress, so removing that from the .rspec file will have no effect, and keeping it in meant the change in spec_helper had no effect.
empirically - used it locally.

spec_helper: allow single spec file to default to document format

---

app/models/hydrus/generic_object.rb
spec/models/hydrus/generic_object_spec.rb

~~Hold until it's clear these are the correct default permissions.~~ Andrew signed off in slack
Fixes #478 - new Hydrus collections have been created with incorrect default permissions for some time now.
on stage; also wrote a test

default collection objects to have world access

---

config/deploy/qa.rb

To let cap deploy to the -qa machine
By deploying this branch
DevOpsDocs PR forthcoming

Deploy hydrus to qa

---

Gemfile
Gemfile.lock

to keep in sync with tiny cocina-models change for a dor-services-app mapping ticket.

update dor-services-client to 6.16
