sul-dlss/hydrus

- spec/features/collection_create_spec.rb
- spec/features/item_create_spec.rb
- spec/features/item_view_spec.rb
- spec/features/models/admin_policy_object_spec.rb
- spec/features/models/collection_spec.rb
- spec/features/models/item_spec.rb
- spec/spec_helper.rb
```
Finished in 6.3 seconds (files took 10.61 seconds to load)
444 examples, 0 failures, 1 pending
...
Finished in 11 minutes 23 seconds (files took 10.44 seconds to load)
120 examples, 0 failures, 8 pending
```
> All tests passing (on the campus network)

- Gemfile
- Gemfile.lock
> Update dor-services to the latest version of the 4.x series

- Capfile
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/deploy.rb
- config/deploy/prod.rb
- config/initializers/squash.rb
> Replace Squash with Honeybadger

- config/application.rb
> Fix duplicate key in hash

- README.md
fixes #7 and more general cleanup
> more updates to the readme

- README.md
sul_chrome gem no longer private and travis not working
> remove travis badge and reference to private sul-chrome gem

- config/deploy.rb
- lib/tasks/hydrus.rake
run this task on deploy automatically
fixes #30
> add a task that indexes all workflow objects into the hydrus solr

- config/initializers/okcomputer.rb
> Add an okcomputer check for client cert connections

- README.md
- lib/tasks/ci.rake
This is just a round about way of calling the ci task.
> Remove local_ci task

- README.md
- app/controllers/hydrus_items_controller.rb
- app/models/hydrus/item.rb
- app/services/item_service.rb
- spec/features/item_create_spec.rb
- spec/features/models/item_spec.rb
- spec/services/item_service_spec.rb
The Item class is too big and the create method has too many lines
> Extract Item.create into ItemService.create

- app/views/hydrus_items/_contributor.html.erb
- app/views/hydrus_items/add_contributor.js.erb
- spec/views/hydrus_items/add_contributor.js.erb_spec.rb
> Pass contributor to avoid an unbound variable

- Gemfile
- README.md
- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
- config/environment.rb
- config/sdr.yml
- devel/run_on_dortest.sh
- lib/tasks/hydrus.rake
- remediations/archive/2013.02.27a.rb
don't merge this yet until we're sure the new servers are good to go.
> Point deploy hosts to new servers

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
> add Coveralls

- spec/factories/user.rb
This avoids a deprecation warning in FactoryBot
> Static attributes will be removed in FactoryBot 5.0

- config/settings/development.yml
I needed to make this update in order to run the `rake hydrus:refreshfix` command when following the current docker instructions.
> Update solr config for dev

- README.md
> Set proper env variable information in the README for development

- app/assets/stylesheets/styles.css.scss
- app/views/hydrus_items/edit.html.erb
These 2 small changes fix the remaining requests from @hannahfrost 
and
> Fix last remaining style requests

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/blacklight.css.scss
- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
> Blacklight 6

- app/assets/javascripts/application.js
See https://nvd.nist.gov/vuln/detail/CVE-2015-9251
> Use Jquery 3 to avoid CVE-2015-9251

- config/settings.yml
- docker-compose.yml
> Provide credentials for dor-services-app

- Gemfile
- Gemfile.lock
- app/models/hydrus/processable.rb
- config/assemblyWF_hydrus.xml
- config/initializers/dor_config.rb
- spec/features/models/item_spec.rb
- spec/models/hydrus/processable_spec.rb
> Removes hydrus-flavored assembly wf in favor of plain-old assembly wf.

- app/models/hydrus/item.rb
- app/models/hydrus/processable.rb
- config/initializers/dor_config.rb
- spec/features/collection_create_spec.rb
- spec/models/hydrus/item_spec.rb
- spec/models/hydrus/processable_spec.rb
> Creates hydrusAssemblyWF instead of creating steps by updating.

- config/initializers/dor_config.rb
- config/settings/development.yml
- config/settings/test.yml
- lib/hydrus.rb
- lib/tasks/fixtures.rake
- spec/features/item_versioning_spec.rb
- spec/fixtures/workflow_xml/druid_oo000oo0000.xml
- spec/fixtures/workflow_xml/druid_oo000oo0001.xml
- spec/fixtures/workflow_xml/druid_oo000oo0002.xml
- spec/fixtures/workflow_xml/druid_oo000oo0003.xml
- spec/fixtures/workflow_xml/druid_oo000oo0004.xml
- spec/fixtures/workflow_xml/druid_oo000oo0005.xml
- spec/fixtures/workflow_xml/druid_oo000oo0006.xml
- spec/fixtures/workflow_xml/druid_oo000oo0007.xml
- spec/fixtures/workflow_xml/druid_oo000oo0008.xml
- spec/fixtures/workflow_xml/druid_oo000oo0009.xml
- spec/fixtures/workflow_xml/druid_oo000oo0010.xml
- spec/fixtures/workflow_xml/druid_oo000oo0011.xml
- spec/fixtures/workflow_xml/druid_oo000oo0012.xml
- spec/fixtures/workflow_xml/druid_oo000oo0013.xml
Workflows are all managed within the workflow-server-rails
> Remove the workflow fixtures.

- app/models/hydrus/admin_policy_object.rb
- app/models/hydrus/collection.rb
- app/models/hydrus/generic_object.rb
- app/models/hydrus/processable.rb
- app/services/item_service.rb
- spec/features/collection_create_spec.rb
- spec/models/hydrus/generic_object_spec.rb
- spec/services/item_service_spec.rb
The dor-services-app no longer starts an initial workflow automatically
> Start workflow after registration

- config/initializers/dor_services_client.rb
- config/settings.yml
Fixes #322 
Merge these first:
https://github.com/sul-dlss/shared_configs/pull/940
https://github.com/sul-dlss/shared_configs/pull/941
> Pass on the dor-services-app token auth

- app/models/hydrus/item.rb
- spec/models/hydrus/item_spec.rb
> Switches to using dor-services-client for closing version.

- Gemfile
- Gemfile.lock
- app/models/hydrus/item.rb
- app/models/hydrus/processable.rb
- app/views/hydrus_items/_actions_box_show.html.erb
- spec/models/hydrus/item_spec.rb
- spec/models/hydrus/processable_spec.rb
> Uses dor services client to check if a new version can be opened.

- Gemfile
- Gemfile.lock
- app/models/hydrus/item.rb
- app/models/hydrus/processable.rb
- app/views/hydrus_items/_actions_box_show.html.erb
- spec/models/hydrus/item_spec.rb
- spec/models/hydrus/processable_spec.rb
And correct `openeable` typo now that DSC uses `openable` instead as of 2.0.0.
Refs https://github.com/sul-dlss/dor-services-app/issues/322
> Bump to dor-services-client 2.0.0 and dor-services 7.2.4

- docker-compose.yml
based on the same fix needed for Argo:  PR sul-dlss/argo/pull/1653 per excellent steer from Mike.
> docker-compose: hook up dor-servcs-app to db

- spec/models/hydrus/item_spec.rb
This wasn't doing anything
n/a
> Remove unnecessary test code

- .travis.yml
- Gemfile.lock
Consistency with all infrastructure projects
n/a
> Upgrade to bundler 2

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/models/hydrus/admin_policy_object.rb
- app/models/hydrus/collection.rb
- app/models/hydrus/generic_object.rb
- app/services/item_service.rb
- config/settings/development.yml
- spec/models/hydrus/generic_object_spec.rb
Update to latest dor-services-client.
No
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.
> Updated to dor-services-client 6.0.

- Gemfile
- Gemfile.lock
See https://github.com/honeybadger-io/honeybadger-ruby/issues/369
> Use a fixed version of honeybadger

- app/services/indexer.rb
- spec/services/indexer_service_spec.rb
Fixes `KeyError: key not found: Hydrus::Collection`
https://app.honeybadger.io/projects/49897/faults/67058057
Added a test to the suite.
> Allow indexing of Hydrus::Collection

- config/deploy.rb
> Update reference from master to main in comment

- .travis.yml
- Gemfile
- Gemfile.lock
> Updated dor-services-client to 6.17.0

- .gitignore
- Gemfile
- Gemfile.lock
- db/schema.rb
> Update to cocina-0.55

- Gemfile
- Gemfile.lock
> Update dor-services-client to 7.0 (cocina-models to 0.61.0)

- lib/tasks/hydrus.rake
refs https://github.com/sul-dlss/happy-heron/issues/1725
We've been asked to do this twice and @peetucket was kind enough to write the rake task so adding to codebase.
Production
NA
> Adds rake task for adding person to collection manager.
